export const ADD_FEEDBACK = "ADD_FEEDBACK"
export const REMOVE_FEEDBACK = "REMOVE_FEEDBACK"

export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"